name: "Deploy pipeline"

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build_push.yml
    secrets: inherit

  terraform:
    uses: ./.github/workflows/terraform.yml
    needs: build
    with:
      frontend_image_tag: ${{ needs.build.outputs.frontend_image_tag }}
      backend_image_tag: ${{ needs.build.outputs.backend_image_tag }}
    secrets: inherit
